[workspace]
resolver = "2"
members  = ["stors-app", "stors-core", "stors-http"]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits      = "release"
opt-level     = 'z'
lto           = true
codegen-units = 1
panic         = "abort"
